distributable:
  url: https://github.com/dbrgn/tealdeer/archive/refs/tags/v{{ version }}.tar.gz
  strip-components: 1

provides:
  - bin/tldr

versions:
  github: dbrgn/tealdeer
  strip: /v/

build:
  dependencies:
    rust-lang.org: '>=1.70'
    rust-lang.org/cargo: '*'
  script: |
    cargo install --locked --path . --root {{prefix}}

test:
  script:
    - test "$(tldr --version)" = "tldr {{version}}"
